image: owitzia/tucker

variables:
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1

build:
  stage: build
  script:
  - mkdir build
  - cd build
  - cmake ../src
  - make
  artifacts:
    paths:
    - build/
       

test:
  stage: test
  script:
  - cd build
  - ctest --output-on-failure
  dependencies:
  - build

pages:
  script:
  - doxygen doxygen/Doxyfile
  - mv doxygen/documentation/html/ public/
  artifacts:
    paths:
    - public
