image: gcc

before_script:
  - apt-get update -qq && apt-get install -y -qq cmake

build:
    stage: build
    script:
       - mkdir build
       - cd build
       - cmake ../src
       - make

test:
    stage: test
    script:
       - ctest