image: gcc

before_script:
- apt-get update -qq && apt-get install -y -qq cmake libopenmpi-dev openmpi-bin liblapack-dev doxygen libjs-mathjax

build:
  stage: build
  script:
  - mkdir build
  - cd build
  - cmake ../src
  - make
  artifacts:
    paths:
    - build/
       

test:
  stage: test
  script:
  - cd build
  - ctest --verbose
  dependencies:
  - build

pages:
  script:
  - doxygen doxygen/Doxyfile
  - mv doxygen/documentation/html/ public/
  artifacts:
    paths:
    - public

