image: gcc:latest

before_script:
- apt-get update
- apt-cache search openmpi
- apt-get install -y cmake libopenmpi3 openmpi-bin liblapack-dev doxygen libjs-mathjax

build:
  stage: build
  script:
  - mkdir build
  - cd build
  - cmake ../src
  - make
  artifacts:
    paths:
    - build/
       

test:
  stage: test
  script:
  - cd build
  - ctest --output-on-failure
  dependencies:
  - build

pages:
  script:
  - doxygen doxygen/Doxyfile
  - mv doxygen/documentation/html/ public/
  artifacts:
    paths:
    - public

