image: gcc

before_script:
  - apt-get update -qq && apt-get install -y -qq cmake libopenmpi-dev openmpi-bin liblapack-dev

build:
    stage: build
    script:
       - mkdir build
       - cd build
       - cmake ../src
       - make

test:
    stage: test
    script:
       - cd build
       - ctest