image: ubuntu:20.04

variables:
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1

before_script:
- DEBIAN_FRONTEND=noninteractive apt-get update
- DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake python libopenmpi3 openmpi-bin liblapack-dev doxygen libjs-mathjax lcov

build:
  stage: build
  script:
  - mkdir build
  - cd build
  - cmake -DMPIEXEC_PREFLAGS="--oversubscribe" ../src
  - make
  artifacts:
    paths:
    - build/
       

test:
  stage: test
  script:
  - cd build
  - export OMP_NUM_THREADS=1
  - ctest --output-on-failure

  dependencies:
  - build

pages:
  script:
  - doxygen doxygen/Doxyfile
  - mv doxygen/documentation/html/ public/
  artifacts:
    paths:
    - public

