# CMake generated Testfile for 
# Source directory: /home/fangq18/TuckerMPI/src/serial/tests
# Build directory: /home/fangq18/TuckerMPI/src/serial/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Tucker_noscale_fullrec_test "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_noscale_fullrec.py")
set_tests_properties(Tucker_noscale_fullrec_test PROPERTIES  LABELS "SystemTest;LongTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;123;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_svd_test "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_svd_test")
set_tests_properties(Tucker_serial_svd_test PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;124;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_svd_test_single "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_svd_test_single")
set_tests_properties(Tucker_serial_svd_test_single PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;125;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_LQ_edgecase_test "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_LQ_edgecase_test")
set_tests_properties(Tucker_serial_LQ_edgecase_test PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;126;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_LQ_edgecase_test_single "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_LQ_edgecase_test_single")
set_tests_properties(Tucker_serial_LQ_edgecase_test_single PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;127;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_LQ_test "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_LQ_test")
set_tests_properties(Tucker_serial_LQ_test PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;128;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_LQ_test_single "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_LQ_test_single")
set_tests_properties(Tucker_serial_LQ_test_single PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;129;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_IO_test "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_IO_test")
set_tests_properties(Tucker_serial_IO_test PROPERTIES  _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;130;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_IO_test_single "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_IO_test_single")
set_tests_properties(Tucker_serial_IO_test_single PROPERTIES  _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;131;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_shift_scale_test "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_shift_scale_test")
set_tests_properties(Tucker_serial_shift_scale_test PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;132;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_shift_scale_test_single "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_shift_scale_test_single")
set_tests_properties(Tucker_serial_shift_scale_test_single PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;133;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_eig_test "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_eig_test")
set_tests_properties(Tucker_serial_eig_test PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;134;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_eig_test_single "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_eig_test_single")
set_tests_properties(Tucker_serial_eig_test_single PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;135;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_norm_test "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_norm_test")
set_tests_properties(Tucker_serial_norm_test PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;136;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_norm_test_single "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_norm_test_single")
set_tests_properties(Tucker_serial_norm_test_single PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;137;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_normalize_test "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_normalize_test")
set_tests_properties(Tucker_serial_normalize_test PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;138;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_normalize_test_single "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_normalize_test_single")
set_tests_properties(Tucker_serial_normalize_test_single PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;139;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_reconstruct_test "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_reconstruct_test")
set_tests_properties(Tucker_serial_reconstruct_test PROPERTIES  _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;140;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_reconstruct_test_single "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_reconstruct_test_single")
set_tests_properties(Tucker_serial_reconstruct_test_single PROPERTIES  _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;141;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_reconstruct_test2 "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_reconstruct_test2")
set_tests_properties(Tucker_serial_reconstruct_test2 PROPERTIES  _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;142;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_reconstruct_test2_single "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_reconstruct_test2_single")
set_tests_properties(Tucker_serial_reconstruct_test2_single PROPERTIES  _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;143;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_gram_test_nofile "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_gram_test_nofile")
set_tests_properties(Tucker_serial_gram_test_nofile PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;144;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_gram_test_nofile_single "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_gram_test_nofile_single")
set_tests_properties(Tucker_serial_gram_test_nofile_single PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;145;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_gram_test_file "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_gram_test_file")
set_tests_properties(Tucker_serial_gram_test_file PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;146;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_gram_test_file_single "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_gram_test_file_single")
set_tests_properties(Tucker_serial_gram_test_file_single PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;147;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_ttm_test_file "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_ttm_test_file")
set_tests_properties(Tucker_serial_ttm_test_file PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;148;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_ttm_test_file_single "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_ttm_test_file_single")
set_tests_properties(Tucker_serial_ttm_test_file_single PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;149;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_ttm_test_nofile "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_ttm_test_nofile")
set_tests_properties(Tucker_serial_ttm_test_nofile PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;150;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_ttm_test_nofile_single "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_ttm_test_nofile_single")
set_tests_properties(Tucker_serial_ttm_test_nofile_single PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;151;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_slice_test_file "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_slice_test_file")
set_tests_properties(Tucker_serial_slice_test_file PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;152;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_slice_test_file_single "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_slice_test_file_single")
set_tests_properties(Tucker_serial_slice_test_file_single PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;153;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_slice_test_nofile "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_slice_test_nofile")
set_tests_properties(Tucker_serial_slice_test_nofile PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;154;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
add_test(Tucker_serial_slice_test_nofile_single "/home/fangq18/TuckerMPI/src/serial/tests/Tucker_slice_test_nofile_single")
set_tests_properties(Tucker_serial_slice_test_nofile_single PROPERTIES  LABELS "UnitTest" _BACKTRACE_TRIPLES "/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;155;ADD_TEST;/home/fangq18/TuckerMPI/src/serial/tests/CMakeLists.txt;0;")
